language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
cache:
  directories:
  - .cachedata
cache: pip

script:
  - git clone https://github.com/digikey/digikey-kicad-library.git .cachedata/digikey-kicad-library
  - python test_login.py

